preprocess: no
load_mel_from_disk: yes
voc:

data:
  featdir: feats
  data_name: chj_22050
  training_files: db/chj_22050/train.txt
  validation_files: db/chj_22050/validation.txt

  batch: [mel, coarse_mel, text, attn_guide, attn_mask]
  is_norm: yes

  length_ratio_max:
  length_ratio_min:
  data_max_text_length: 400
  data_max_mel_length: 480

  text_cleaners: ['korean_cleaners']
  sampling_rate: 22050
  audio_refdB: 20
  audio_maxdB: 100
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  n_mel: 80
  segment_length:
  max_wav_value: 32768.0
  reduction_factor: 4

train:
  adversarial_training: no
  module: ssrn
  distributed_run: no

  tensorboard_dir: log
  exp_directory: exp
  exp_name: ssrn_norm_feat
  checkpoint: exp/dctts_v2/ssrn_norm_feat/checkpoint_243500

  batch_size: 32
  reduction_factor: 4
  epoch: 800

  valid_epoch: 5
  valid_num: 5
  loss_snapshot_step: 100
  save_epoch: 5

  ngpu: 1
  device: cuda:0

  guided_attention:
    guide_g: 0.2
    guide_weight: 100.0
    guide_decay: 0.99999
    guide_lowbound: 1

optimizer:
  adam_alpha: 2e-4
  adam_beta1: 0.5
  adam_beta2: 0.9
  adam_eps: 1e-6

model:
  fdim: 80
  edim: 128
  ddim: 256
  dropout_rate: 0.05
