data:
  featdir: feats
  data_name: SMART_TTS
  training_files: db/SMART_TTS/train.txt
  validation_files: db/SMART_TTS/valid.txt

  batch: [mel_seg, audio_seg]

  text_cleaners:
  sampling_rate: 22050
  audio_refdB: 20
  audio_maxdB: 100
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  n_mel: 80
  segment_length: 8192
  max_wav_value: 32768.0
  reduction_factor: 1

train:
  device: [3]

  adversarial_training: yes
  distributed_run: no

  checkpoint:
  exp_directory: exp
  exp_name: developing_model
  tensorboard_dir: log

  batch_size: 32
  epoch: 4000

  valid_epoch: 5
  valid_num: 5
  loss_snapshot_step: 100
  save_epoch: 5

optimizer:
  adam_alpha: 1e-4
  adam_beta1: 0.5
  adam_beta2: 0.9

model:
  feat_match: 10.0
  g:
    mel_channels: 80
    ngf: 32
    n_residual_layers: 3

  d:
    num_D: 3
    ndf: 16
    n_layers_D: 4
    downsampling_factor: 4


